// ELEMENTOS HTML
const overlay = document.getElementsByClassName("pushbar_overlay")
const navMenu = document.getElementById("nav-menu")
const closeMenu = document.getElementById("close-menu")
const noResultItem = document.getElementsByClassName("noResult-item")
const aside = document.getElementById("desktop-aside")
const header = document.querySelector("header")
const logo = document.getElementById("logo")
const barras= document.getElementById("barras")
const main = document.querySelector("main")
const resultadoFinalMobile =  document.getElementById("result-area-mobile")
const resultadoMobile = document.getElementById("result-mobile")
const resultado = document.getElementById("result-area")
const textarea = document.getElementById("textarea-principal")
const contenido = document.getElementById("textarea-principal").innerHTML
const noResultDesktop = document.getElementById("noResult-desktop")
const resultDesktop = document.getElementById("result-desktop")
const noResult = document.getElementById("noResult")
const encButton = document.getElementById("encButton")
const dencButton = document.getElementById("dencButton")
const copyButtton= document.getElementsByClassName("copy-button")
const copyButttonDesktop= document.getElementById("copyDesktop")
const copyButttonMobile= document.getElementById("copyMobile")
const completeHtml= () => window.innerWidth
